FROM ghcr.io/taitounited/taito-cli-deps:ci
MAINTAINER Taito United <support@taitounited.fi>

# Install dockerd
# On some environments (e.g. AWS CodeBuild) dockerd must be running when
# building docker images
RUN /taito-cli-deps/tools/install-dockerd-bin.sh
