FROM ghcr.io/taitounited/taito-cli-deps:ci
MAINTAINER Taito United <support@taitounited.fi>

# Install dockerd
# On AWS CodeBuild dockerd must be running when building docker images
RUN /taito-cli-deps/tools/install-dockerd-bin.sh

# Install aws cli and aws-iam-authenticator
RUN /taito-cli-deps/tools/install-python3.sh
RUN /taito-cli-deps/tools/install-aws.sh
