FROM ghcr.io/taitounited/taito-cli-deps:ci
MAINTAINER Taito United <support@taitounited.fi>

# Install Kubectl for deploying to Kubernetes
RUN /taito-cli-deps/tools/install-kubectl.sh

# Install Helm for deploying to Kubernetes
RUN /taito-cli-deps/tools/install-helm.sh

# Install Terraform for deploying configuration changes to cloud
RUN /taito-cli-deps/tools/install-terraform.sh

# Install database tools for deploying database migrations to database
RUN /taito-cli-deps/tools/install-db-clients.sh
RUN /taito-cli-deps/tools/install-sqitch.sh

# Initialize taito user
RUN /taito-cli-deps/tools/user-init.sh taito
