FROM ghcr.io/taitounited/taito-cli-deps:ci-deploy
MAINTAINER Taito United <support@taitounited.fi>

# Install gcloud sdk
ENV PATH "$PATH:/opt/google-cloud-sdk/bin/"
RUN /taito-cli-deps/tools/install-gcloud.sh
