FROM debian:bullseye-slim
MAINTAINER Taito United <support@taitounited.fi>

ARG TARGETPLATFORM
ENV TARGETPLATFORM ${TARGETPLATFORM}

USER root
COPY . /taito-cli-deps
WORKDIR /tmp

# Install some basic tools
RUN /taito-cli-deps/tools/install-basic.sh

# Install Node.js for executing npm commands and running Node.js builds
RUN /taito-cli-deps/tools/install-nodejs.sh

# Install yamljs for yaml-json conversions (small size)
RUN npm install -g yamljs

# Install Google Cloud SQL proxy (db proxy for test suites, db migrations, etc.)
RUN /taito-cli-deps/tools/install-gcloud-sql-proxy.sh

# Initialize root user
RUN /taito-cli-deps/tools/user-init.sh root
