FROM ghcr.io/taitounited/taito-cli-deps:base
MAINTAINER Taito United <support@taitounited.fi>

# TODO: Backwards compatibility for auth sessions. Remove later.
RUN mkdir -p /builder/google-cloud-sdk/bin && \
    ln -s /usr/bin/gcloud /builder/google-cloud-sdk/bin/gcloud

# Install bats for Taito CLI unit testing
RUN /taito-cli-deps/tools/install-bats.sh

# Install python3
RUN /taito-cli-deps/tools/install-python3.sh

# Install Kubectl for Kubernetes
RUN /taito-cli-deps/tools/install-kubectl.sh

# Install Helm for Kubernetes
RUN /taito-cli-deps/tools/install-helm.sh

# Install Terraform for cloud
RUN /taito-cli-deps/tools/install-terraform.sh

# Install database tools
RUN /taito-cli-deps/tools/install-db-clients.sh
RUN /taito-cli-deps/tools/install-sqitch.sh

# Install depcheck for checking npm dependencies
RUN npm install depcheck npm-check -g

# Install ansible
RUN /taito-cli-deps/tools/install-ansible.sh

# Install aws cli and aws-iam-authenticator for AWS
RUN /taito-cli-deps/tools/install-aws.sh

# Install Azure CLI
RUN /taito-cli-deps/tools/install-azure-cli.sh

# Install gcloud sdk for GCP
ENV PATH "$PATH:/opt/google-cloud-sdk/bin/"
RUN /taito-cli-deps/tools/install-gcloud.sh

# Install gcsfuse for mounting GCP storage buckets
# RUN /taito-cli-deps/tools/install-gcsfuse.sh

# Install digitalocean cli
RUN /taito-cli-deps/tools/install-do.sh

# Install OpenShift cli
RUN /taito-cli-deps/tools/install-openshift-cli.sh

# Install Argo CLI
RUN /taito-cli-deps/tools/install-argo-cli.sh

# Install docker (required for executing CI/CD builds on container)
RUN /taito-cli-deps/tools/install-docker-bin.sh

# Install some extra tools for local use of Taito CLI
RUN apt-get -y update && \
    apt-get -y install \
      easy-rsa \
      perl-doc \
      git \
      less \
      telnet \
      apache2-utils \
      vim \
      nano \
      pwgen \
      xkcdpass \
      uuid-runtime \
      groff \
      zip \
      dnsutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV EDITOR=/bin/nano
