FROM debian:bookworm-20231218-slim
MAINTAINER Taito United <support@taitounited.fi>

ARG TARGETPLATFORM
ENV TARGETPLATFORM ${TARGETPLATFORM}

USER root
COPY . /taito-cli-deps
WORKDIR /tmp

# Install some basic tools
RUN /taito-cli-deps/tools/install-basic.sh

# Set default locale
RUN dpkg-reconfigure locales && \
  locale-gen C.UTF-8 && \
  /usr/sbin/update-locale LANG=C.UTF-8
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && \
  locale-gen
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

# Install Node.js for executing npm commands and running Node.js builds
RUN /taito-cli-deps/tools/install-nodejs.sh

# Install yamljs for yaml-json conversions (small size)
RUN npm install -g yamljs

# Install Google Cloud SQL proxy (db proxy for test suites, db migrations, etc.)
RUN /taito-cli-deps/tools/install-gcloud-sql-proxy.sh

# Initialize root user
RUN /taito-cli-deps/tools/user-init.sh root
