FROM ghcr.io/taitounited/taito-cli-deps:base
MAINTAINER Taito United <support@taitounited.fi>

# Install docker (required for executing CI/CD builds on container)
RUN /taito-cli-deps/tools/install-docker-bin.sh

# Install docker-compose (required for CI/CD tests)
RUN /taito-cli-deps/tools/install-docker-compose.sh
