FROM taitounited/taito-cli-ci
MAINTAINER Taito United <support@taitounited.fi>

# Install digitalocean cli
ENV DO_VERSION 1.30.0
RUN /taito-cli-deps/tools/install-do.sh

# Install gcloud sdk (for GCP CI builds)
ENV CLOUD_SDK_VERSION=259.0.0
ENV PATH "$PATH:/opt/google-cloud-sdk/bin/"
RUN /taito-cli-deps/tools/install-gcloud.sh

ENTRYPOINT ["bash"]
