---
name: 'build images'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ci-deploy
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-deploy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-deploy

      - name: Build ci-all
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-all
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-all

      - name: Build ci-aws
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-aws
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-aws

      - name: Build ci-azure
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-azure
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-azure

      - name: Build ci-do
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-do
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-do

      - name: Build ci-gcp
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-gcp
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-gcp

      - name: Build ci-openshift
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-openshift
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:ci-openshift

      - name: Build all
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-all
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/taitounited/taito-cli-deps:all
