---
name: "build images"

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            tag: amd64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            tag: arm64
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}

          SUFFIX="-${BRANCH}"
          if [ ${GITHUB_REF} != ${TAG} ]; then
            SUFFIX="-${TAG}"
          fi
          if [ ${BRANCH} = "master" ]; then
            SUFFIX=
          fi

          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "SUFFIX=${SUFFIX}" >> $GITHUB_ENV
          echo "TAGDATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-base
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:base${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build cli
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-cli
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:cli${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-dockerd
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-dockerd
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-dockerd${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-deploy
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-deploy
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-deploy${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-all
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-all
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-all${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-aws
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-aws
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-aws${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-azure
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-azure
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-azure${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-do
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-do
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-do${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-gcp
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-gcp
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-gcp${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build ci-openshift
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-ci-openshift
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:ci-openshift${{ env.SUFFIX }}-${{ matrix.tag }}

      - name: Build all
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile-all
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/taitounited/taito-cli-deps:all${{ env.SUFFIX }}-${{ matrix.tag }}

  manifest:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set environment
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=${GITHUB_REF#refs/tags/}

          SUFFIX="-${BRANCH}"
          if [ ${GITHUB_REF} != ${TAG} ]; then
            SUFFIX="-${TAG}"
          fi
          if [ ${BRANCH} = "master" ]; then
            SUFFIX=
          fi

          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          echo "SUFFIX=${SUFFIX}" >> $GITHUB_ENV
          echo "TAGDATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:base${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:base${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:base${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:base${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:cli${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:cli${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:cli${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:cli${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-dockerd${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-dockerd${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-dockerd${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-dockerd${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-deploy${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-deploy${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-deploy${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-deploy${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-all${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-all${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-all${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-all${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-aws${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-aws${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-aws${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-aws${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-azure${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-azure${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-azure${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-azure${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-do${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-do${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-do${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-do${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-gcp${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-gcp${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-gcp${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-gcp${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:ci-openshift${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:ci-openshift${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:ci-openshift${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:ci-openshift${{ env.SUFFIX }}-arm64

      - run: |
          docker buildx imagetools create \
            -t ghcr.io/taitounited/taito-cli-deps:all${{ env.SUFFIX }} \
            -t ghcr.io/taitounited/taito-cli-deps:all${{ env.SUFFIX }}-${{ env.TAGDATE }} \
            ghcr.io/taitounited/taito-cli-deps:all${{ env.SUFFIX }}-amd64 \
            ghcr.io/taitounited/taito-cli-deps:all${{ env.SUFFIX }}-arm64
